{{- if .Values.genericSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.genericSecret.name }}
spec:
  refreshInterval: {{ .Values.genericSecret.refreshInterval | default "30s" }}
  secretStoreRef:
    name: {{ .Values.genericSecret.secretStoreRef.name }}
    kind: {{ .Values.genericSecret.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ .Values.genericSecret.name }}
  data:
{{ toYaml .Values.genericSecret.data | indent 4 }}
{{- end }}

{{- if .Values.dockerconfigjson.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.dockerconfigjson.name }}
spec:
  refreshInterval: {{ .Values.dockerconfigjson.refreshInterval | default "30s" }}
  secretStoreRef:
    name: {{ .Values.dockerconfigjson.secretStoreRef.name }}
    kind: {{ .Values.dockerconfigjson.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ .Values.dockerconfigjson.name }}
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{{ printf "{{ `{{ .%s }}` }}" .Values.dockerconfigjson.dockerconfigjsonKey }}'
  data:
{{ toYaml .Values.dockerconfigjson.data | indent 4 }}
{{- end }}
